Load Cookie With Consent
prebid/prebid-universal-creative pull request #123
Opened 2020-10-08 17:29 UTC by mmoschovas

Created alternate to load-cookie.html named load-cookie-with-consent.html. This will load the new cookieSyncWithConsent.js script which will postMessage the parent window for GDPR consent data. If data is returned before the timeout, the data is parsed to retrieve the gdprApplies and consentString values, which are then set in the data of the Prebid Server request. If the timeout expires prior to data returning, the defaultGdprScope setting will determine if the user sync should still run or not. The below fields can be passed in the load-cookie-with-consent.html URL string.

_defaultGdprScope_ : accepted values 0 or 1, default 1
_timeout_ : integer, default 10000

i.e. The blow example would set the timeout to 500ms and allow sync if timeout is reached and GDPR data is not returned 
...load-cookie-with-consent.html?max_sync_count=5&timeout=500&defaultGdprScope=0

2020-10-14 13:54 UTC, bretg commented
Thanks @mmoschovas . For the record, this is the code for https://github.com/prebid/prebid-universal-creative/issues/114

2020-10-14 14:20 UTC, bretg commented
I'll take a cut at the docs.

2020-10-20 13:17 UTC, Fawke requested changes
Tested the example amp page on a few browsers, seems to be working fine. Just had one small issue, please check the line comment.

2020-10-21 16:50 UTC, mmoschovas commented on src/cookieSyncWithConsent.js
> +/**
Updated comment

2020-10-23 12:02 UTC, Fawke approved these changes
LGTM.

2020-10-29 23:57 UTC, bretg commented
docs PR https://github.com/prebid/prebid.github.io/pull/2456

2020-11-24 05:24 UTC, harpere approved these changes

2021-01-12 18:02 UTC, merged